/**
 * @deprecated Import from `@core/constants/in-view-reveal` instead.
 * Re-exports kept so existing carousel imports keep working.
 */
export {
  IN_VIEW_REVEAL_DURATION_MS as SCROLL_CAROUSEL_REVEAL_DURATION_MS,
  IN_VIEW_REVEAL_STAGGER_MS as SCROLL_CAROUSEL_REVEAL_STAGGER_MS,
  IN_VIEW_REVEAL_TRANSLATE_Y as SCROLL_CAROUSEL_REVEAL_TRANSLATE_Y,
  IN_VIEW_REVEAL_EASE as SCROLL_CAROUSEL_REVEAL_EASE,
  IN_VIEW_REVEAL_ROOT_MARGIN as SCROLL_CAROUSEL_REVEAL_ROOT_MARGIN,
  IN_VIEW_REVEAL_THRESHOLD as SCROLL_CAROUSEL_REVEAL_THRESHOLD,
} from "@core/constants/in-view-reveal";
